import * as React from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';
import '@/styles/root/root.scss';
import '@/styles/common/container.scss';
import Header from '@/components/Header/Header';
import Footer from '@/components/Footer/Footer';
import Login from './(auth)/login/page';
import Provider from '@/utils/Provider';
import { cn } from '@/lib/utils';
import { ThemeProvider } from '@/components/theme-provider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import AuthProvider from '@/context/authProvider';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['vietnamese'] });
const fontInter = localFont({
	src: [
		{
			path: '../fonts/Inter/Inter-Regular.woff2',
			weight: '400',
			style: 'normal',
		},
		{
			path: '../fonts/Inter/Inter-Medium.woff2',
			weight: '500',
			style: 'normal',
		},
		{
			path: '../fonts/Inter/Inter-SemiBold.woff2',
			weight: '600',
			style: 'normal',
		},
		{
			path: '../fonts/Inter/Inter-Bold.woff2',
			weight: '700',
			style: 'normal',
		},
		{
			path: '../fonts/Inter/Inter-Bold.woff2',
			weight: 'bold',
			style: 'normal',
		},
	],
});

const fontBebas = localFont({
	src: [
		{
			path: '../fonts/Bebas/BebasNeue-Regular.ttf',
			weight: '400',
			style: 'normal',
		},
	],
});

export const metadata: Metadata = {
	title: 'Mona.host',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	const cookieStore = cookies();
	const sessionToken = cookieStore.get('sessionToken');
	return (
		<html lang='en'>
			<body className={`${cn('container-lg min-h-screen font-sans antialiased')}${fontInter.className}`}>
				{/* <div className={`cart-mini fixed inset-0 z-50 ${isDrawerOpen ? 'open' : ''}`}>
					<Cart onCartIconClick={handleCartIconClick} />

					<div
						className='cart-mini-overlay fixed inset-0 bg-black-20 -z-10'
						onClick={handleCartIconClick}
					></div>
				</div> */}

				<Provider>
					<AuthProvider initialSessionToken={sessionToken?.value}>
						<ThemeProvider>
							<Header />
							<main className='main'>{children}</main>
							<Footer />
							<ToastContainer />
						</ThemeProvider>
					</AuthProvider>
				</Provider>
			</body>
		</html>
	);
}
